/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./src/components/ContactPage.vue')['default']
    ContactPage: typeof import('./src/components/ContactPage.vue')['default']
    Fashion: typeof import('./src/components/FashionTable.vue')['default']
    FashionTable: typeof import('./src/components/FashionTable.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LLMChat: typeof import('./src/components/LLMChat.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    ParallaxScroll: typeof import('./src/components/ParallaxScroll.vue')['default']
    PhoneMusic: typeof import('./src/components/PhoneMusic.vue')['default']
    PreviewCard: typeof import('./src/components/PreviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecretPage: typeof import('./src/components/SecretPage.vue')['default']
  }
}
